### PR TITLE
Add arm64 x86_64 support

### LINKED ISSUE #1836: [Bug]Broken support for android ndk build when deal with arm64
If you want to build arm64 with armeabv7a, you have to set  `app_platform = android-21`  above.

Repro repo: https://github.com/gengjiawen/android-jsc/tree/feature/abi_support.

Suggest fix: when deal with arm64, automatically use `android-21`, in other case, use `android-16` or something like that.

### PR DESCRIPTION
**Pull request by gengjiawen**
[Build Status](https://travis-ci.org/gengjiawen/android-jsc)
* add arm64 x86_64 support
* ci support (I switch to travis because they circle ci won't provide 8g machine for open source project)

Some bug in buck need to be fixed: https://github.com/facebook/buck/issues/1836. After they fix it. We need another pr to fix app modules thing.

### CODE REVIEW

**Comment by rzsombor** [comment]
How does this PR relate to https://github.com/facebook/android-jsc/pull/19 ?

**Comment by gengjiawen** [comment]
This pr is based on that pr, you can see the cherry commit from that pr. Besides that I fix broken url and add ci.

**Comment by leeight** [comment]
Cool.

**Comment by LegNeato** [comment]
The buck change landed: https://github.com/facebook/buck/commit/fe15dae213ac0e64886157cd513b043269f68edb

**Comment by hramos** [comment]
https://github.com/facebook/react-native/pull/18754 has been merged. What's next?

**Comment by gengjiawen** [comment]
Do you have merge permission to this repo ? we may still need a repo to handle jsc thing if we don't adopt the jsc from community.

**Comment by AustinHunt** [comment]
Is this ever happening?

**Comment by hramos** [comment]
This PR was opened as part of an effort to add 64-bit library support to React Nartive. We already have 64-bit support in the JSC that is being used by React Native. The JSC used there is built based on a different repository than this.

If you’re interested in seeing 64-bit support added to the JSC in this repository for use with something other than React Native, then I probably am not the right person to help.

**Comment by AustinHunt** [comment]
Well, the android version of React Native currently does not support Javascript Proxy...which is why I was using this JSC. But, this JSC does not work on Android 9 x86_64 devices.

**Pull request closed without merging**
